### ISSUE TITLE
get_api_interface() infinite retries with run_service_once()

### ISSUE THREAD

**Issue by Acke0** [CybercentreCanada/assemblyline-v4-service#434]
Hello,

I have been using get_api_interface() in order to get the safelist. It works well but when I run the service with `python -m assemblyline_v4_service.dev.run_service_once` it goes in an infinite loop, trying to reach the ServiceAPI :
https://github.com/CybercentreCanada/assemblyline-v4-service/blob/d646d12d10d59c1a742fefbee18f86482e6e4e4f/assemblyline_v4_service/common/api.py#L49-L56

Should it raise an exception for when it reaches a certain number of retries ? Or maybe I'm missing a way to avoid this.
My code does this, currently I catch the ServiceAPIError:
```python
try:
    self.safelist = self.get_api_interface().get_safelist()
except ServiceAPIError as err:
    self.log.warning(f"Couldn't retrieve safelist from service: {err}. Continuing without it..")
```

**version** : *4.2.0.stable118*

**Comment by cccs-sgaron** [comment]
I'm not a big fan of the service havnig to try catch the get_api_interface calls just for debugging. I think instead we should have a way to detect that a service is not launched into a normal service execution context and have the get_api_interface return empty safelist when its called. This will essentially do the same thing and the service writer wont have to worry about it.

**Comment by cccs-kevin** [comment]
bump

**Comment by Acke0** [comment]
`run_service_once` could set an env like `ALDEBUG` to 1 or else and `get_api_interface` would check this value ?
