### ISSUE TITLE
Service submission parameter not found

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline-v4-service#495]
When submitting via the API, I was getting the exception of `Service submission parameter not found`.  I was expecting it to use the default defined in the user configuration if not submitted with the request.  My initial intent was just to create a PR to add a default variable to `get_param` such as `default: Optional[Union[bool, int, str, list]] = None` that gets passed to task and then I could define it in the service.  However, should you instead try to pull the default from the config?  If config is not accessible from request, then yeah, perhaps the default variable that we can set either manually or by calling the config.  If no default as a required user option, then raise the exception.

https://github.com/CybercentreCanada/assemblyline-v4-service/blob/1a5b49d66d95342dc60da85897f520b55a1fbc00/assemblyline_v4_service/common/request.py#L163-L169

https://github.com/CybercentreCanada/assemblyline-v4-service/blob/1a5b49d66d95342dc60da85897f520b55a1fbc00/assemblyline_v4_service/common/task.py#L172-L177

**Comment by cccs-rs** [comment]
This should be resolved with services built from [4.3.1.7](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.3.1.stable7)
